/* eslint-disable react/no-unescaped-entities */
'use client';
import Link from 'next/link';

export default function Privacy() {
  return (
    <div className="px-20">
      <p className="font-semibold text-4xl text-center m-10">Privacy Policy</p>

      <div className="p-8 bg-white shadow-md rounded-md">
        <h1 className="text-xl font-bold mb-10">Updated: 12th February 2024</h1>

        <div className="mb-10">
          <h2 className="text-xl font-semibold mb-2">1. Introduction</h2>
          <p>
            Welcome to InGrow. InGrow ('us', 'we', or 'our') operates the
            website located at
            <Link
              href="http://www.ingrow.pro/"
              target="_blank"
              className="text-blue-primary mx-1"
            >
              www.ingrow.pro
            </Link>
            ('Service'). This Privacy Policy outlines how we collect, safeguard,
            and disclose information resulting from your use of our Service. By
            using the Service, you consent to the collection and use of
            information in accordance with this policy.
          </p>
        </div>

        <div className="mb-10">
          <h2 className="text-xl font-semibold mb-2">2. Definitions</h2>
          <ul className="list-disc list-inside">
            <li className="my-2">
              <span className="font-semibold mr-2">SERVICE</span>
              <span>
                refers to the website operated by InGrow accessible at
                <Link
                  href="http://www.ingrow.pro/"
                  target="_blank"
                  className="text-blue-primary mx-1"
                >
                  www.ingrow.pro
                </Link>
                .
              </span>
            </li>
            <li className="my-2">
              <span className="font-semibold mr-2">PERSONAL DATA</span>
              means data about a living individual who can be identified from
              those data.
            </li>
            <li className="my-2">
              <span className="font-semibold mr-2">USAGE DATA</span>
              is data collected automatically, generated by the use of the
              Service or from the Service infrastructure itself.
            </li>
            <li className="my-2">
              <span className="font-semibold mr-2">COOKIES</span>
              are small files stored on your device.
            </li>
            <li className="my-2">
              <span className="font-semibold mr-2">DATA CONTROLLER</span>
              means data about a living individual who can be identified from
              those data.
            </li>
            <li className="my-2">
              <span className="font-semibold mr-2">
                DATA PROCESSORS (OR SERVICE PROVIDERS)
              </span>
              are any natural or legal person who processes the data on behalf
              of the Data Controller.
            </li>
            <li className="my-2">
              <span className="font-semibold mr-2">DATA SUBJECT</span>
              is any living individual who is the subject of Personal Data.
            </li>
            <li className="my-2">
              <span className="font-semibold mr-2">THE USER</span>
              is the individual using our Service, corresponding to the Data
              Subject.
            </li>
          </ul>
        </div>

        <div className="mb-10">
          <h2 className="text-xl font-semibold mb-2">
            3. Information Collection and Use
          </h2>
          <p>
            We collect several types of information for various purposes to
            provide and improve our Service.
          </p>
        </div>

        <div className="mb-10">
          <h2 className="text-xl font-semibold mb-2">
            4. Types of Data Collected
          </h2>
          <div className="mb-2">
            <span className="font-semibold text-lg mr-1">Personal Data:</span>
            <ul className="list-disc list-inside">
              <li className="my-1">Email address</li>
              <li className="my-1">Cookies and Usage Data</li>
            </ul>
          </div>
          <div className="mb-2">
            <span className="font-semibold text-lg">Usage Data:</span>
            <p>
              We collect information your browser sends whenever you visit our
              Service or access the Service via a mobile device.
            </p>
          </div>
          <div className="mb-2">
            <span className="font-semibold text-lg mr-1">
              Tracking & Cookies Data:
            </span>
            <span>
              We use cookies and similar tracking technologies to monitor
              activity on our Service and store certain information. You can
              instruct your browser to refuse all cookies or indicate when a
              cookie is being sent.
            </span>
          </div>
        </div>
        <div className="mb-10">
          <h2 className="text-xl font-semibold mb-2">Use of Data</h2>
          <p>InGrow uses the collected data to:</p>
          <ul className="list-disc list-inside">
            <li className="my-1">Provide and maintain our Service</li>
            <li className="my-1">Notify you about changes to our Service</li>
            <li className="my-1">
              Allow interactive features when you choose to use them
            </li>
            <li className="my-1">Provide customer support</li>
            <li className="my-1">Gather analysis to improve our Service</li>
            <li className="my-1">Monitor the usage of our Service</li>
            <li className="my-1">
              Detect, prevent, and address technical issues
            </li>
          </ul>
        </div>
        <div className="mb-10">
          <h2 className="text-xl font-semibold mb-2">6. Retention of Data</h2>
          <p>
            We will retain your Personal Data only for as long as necessary for
            the purposes set out in this Privacy Policy.
          </p>
        </div>
        <div className="mb-10">
          <h2 className="text-xl font-semibold mb-2">7. Transfer of Data</h2>
          <p>
            Your information, including Personal Data, may be transferred to
            computers located outside your state, province, country, or other
            governmental jurisdiction where data protection laws may differ.
          </p>
        </div>
        <div className="mb-10">
          <h2 className="text-xl font-semibold mb-2">Disclosure of Data</h2>
          <p>
            We may disclose your Personal Data in the good faith belief that
            such action is necessary to:
          </p>
          <ul className="list-disc list-inside">
            <li className="my-1">Comply with a legal obligation</li>
            <li className="my-1">Protect and defend our rights or property</li>
            <li className="my-1">
              Prevent or investigate possible wrongdoing in connection with the
              Service
            </li>
            <li className="my-1">
              Protect the personal safety of users of the Service or the public
            </li>
            <li className="my-1">Protect against legal liability</li>
          </ul>
        </div>
        <div className="mb-10">
          <h2 className="text-xl font-semibold mb-2">9. Security of Data</h2>
          <p>
            The security of your data is important to us but remember no method
            of transmission over the internet or electronic storage is 100%
            secure.
          </p>
        </div>

        <div className="mb-10">
          <h2 className="text-xl font-semibold mb-2">10. Service Providers</h2>
          <p>
            We may employ third-party companies and individuals to facilitate
            our Service, provide the Service on our behalf, perform
            Service-related services, or assist us in analyzing how our Service
            is used.
          </p>
        </div>

        <div className="mb-10">
          <h2 className="text-xl font-semibold mb-2">11. Analytics</h2>
          <p>
            We may use third-party Service Providers to monitor and analyze the
            use of our Service.
          </p>
        </div>

        <div>
          <h2 className="text-xl font-semibold mb-2">Contact Us</h2>
          <p>
            For any questions about this Privacy Policy, please contact us at{' '}
            <Link href="mailto:akshay@ingrow.pro" className="text-blue-primary">
              akshay@ingrow.pro
            </Link>
            .
          </p>
        </div>
      </div>
    </div>
  );
}
